language: java
jdk: oraclejdk8
addons:
  sonarcloud:
    organization: "fjp1jlkt1iuh4afm159x760xoz81xl3"
    token: $SONAR_TOKEN
script:
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: mlgalaxy